name: ga_sync
description: >-
  A CLI tool to sync Google Analytics event definitions and page paths
  between spreadsheets and code.
version: 0.1.0
repository: https://github.com/anies1212/ga_sync

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.0
  googleapis: ^13.0.0
  googleapis_auth: ^1.4.0
  yaml: ^3.1.0
  path: ^1.8.0
  code_builder: ^4.10.0
  dart_style: ^2.3.0
  analyzer: ^6.0.0
  http: ^1.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  mockito: ^5.4.0
  build_verify: ^3.1.0

executables:
  ga_sync: ga_sync
